#ifndef CALLBACK_H_INCLUDED_
#define CALLBACK_H_INCLUDED_


#include <stdint.h>


typedef int32_t _size_t;

typedef int32_t _mouse_button_t;
typedef int32_t _mouse_button_state_t;

typedef uint8_t _key_t;
typedef int32_t _special_key_t;


/**
 * Sets defined callback functions.
 */
void initCallbacks(void);

/**
 * Current window display callback function.
 */
void display(void);

/**
 * Current window reshape callback.
 * 
 * @param width New current window width.
 * @param height New current window height.
 */
void reshape(_size_t width, _size_t height);

/**
 * Mouse callback function.
 * 
 * @param button Pressed or released button.
 *               One of @c GLUT_LEFT_BUTTON,
 *                      @c GLUT_MIDDLE_BUTTON or
 *                      @c GLUT_RIGHT_BUTTON.
 * @param state Indicate whether button was pressed or released.
 *              One of @c GLUT_DOWN or @c GLUT_UP respectively.
 */
void mouse(
    _mouse_button_t button,
    _mouse_button_state_t state,
    int32_t x, int32_t y
);

/**
 * Keyboard callback function.
 * 
 * @param key ASCII character generated by key pressing.
 */
void keyboard(_key_t key, int32_t x, int32_t y);

/**
 * Special keyboard callback function.
 * 
 * @param key One of the predefined values representing
 *            special keyboard key
 *            such as function and directional keys.
 */
void specialKeyboard(
    _special_key_t key,
    int32_t x, int32_t y
);


#endif  /* CALLBACK_H_INCLUDED_ */
